Repository cloudfoundry/metric-store-release, pull requests merged in 2020-09, with the labels that each got.

#121 Auto Bump Golang Release v0.64.0
  .final_builds/packages/golang-1-linux/index.yml
  packages/golang-1-linux/spec.lock
Labels: unscheduled

#122 Remove healthwatch scraping and config
  jobs/metric-store/spec
  jobs/metric-store/templates/certs/healthwatch_exporter.crt.erb
  jobs/metric-store/templates/certs/healthwatch_exporter.key.erb
  jobs/metric-store/templates/certs/healthwatch_exporter_ca.crt.erb
  jobs/metric-store/templates/scrape_config.yml.erb
  tile/instance_groups/metric_store.yml
  tile/jobs/metric-store.yml
Labels: scheduled

#130 Auto Bump Golang Release v0.66.0
  .final_builds/packages/golang-1-linux/index.yml
  packages/golang-1-linux/spec.lock
Labels: auto-merge, unscheduled
